version: '3.7'

services:
  api:
    build:
      context:  ./services/flask
      dockerfile: Dockerfile.prod
    container_name: flask_api
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
