version: '3.7'

services:
  api:
    build:
      context:  ./services/flask
      dockerfile: Dockerfile
    container_name: flask_api
    # command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/flask/:/usr/src/app/
    ports: 
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  nginx:
    container_name: nginx
    build:
      context:  ./services/nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
