version: '3.7'

services:
  flask_api:
    build:
      context:  ./services/flask
      dockerfile: Dockerfile
    container_name: flask_api # Do not use when in a swarm; cannot scale a service beyond 1 container if you have specified a custom name
    volumes:
      - ./services/flask/:/usr/src/app/
    ports: 
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    container_name: mongo_db
    image: mongo
    command: mongod --auth
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    env_file:
      - ./.env.dev.db

  nginx:
    container_name: nginx
    build:
      context:  ./services/nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - flask_api
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodb_data:

