version: '3.7'

services:
  keystore:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup/
    env_file:
      - dev.env
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
  certs:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup/
    env_file:
      - dev.env
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
